version: "3"

services:
  react_min_pp_digital:
    container_name: react_min_pp_digital
    image: react_min_pp_digital:1.0
    build: .
    command: npm start
    ports:
      - "4020:4020"
    volumes:
      - static_volume:/home/react_app/
    networks:
      - app_aposta_postgres

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/react_app/
    ports:
      - "8020:73"
    networks:
      - app_aposta_postgres
    depends_on:
      - react_min_pp_digital

volumes:
  static_volume:

networks:
  app_aposta_postgres:
    external: true
